// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Retail.Infrastructure;

#nullable disable

namespace Retail.Migrations
{
    [DbContext(typeof(RetailContext))]
    [Migration("20240415011007_Cargar datos productos")]
    partial class Cargardatosproductos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Retail.Domain.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategoryId");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "Electrodomésticos"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "Tecnología y Electrónica"
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "Moda y Accesorios"
                        },
                        new
                        {
                            CategoryId = 4,
                            Name = "Hogar y Decoración"
                        },
                        new
                        {
                            CategoryId = 5,
                            Name = "Salud y Belleza"
                        },
                        new
                        {
                            CategoryId = 6,
                            Name = "Deportes y Ocio"
                        },
                        new
                        {
                            CategoryId = 7,
                            Name = "Juguetes y Juegos"
                        },
                        new
                        {
                            CategoryId = 8,
                            Name = "Alimentos y Bebidas"
                        },
                        new
                        {
                            CategoryId = 9,
                            Name = "Libros y Material Educativo"
                        },
                        new
                        {
                            CategoryId = 10,
                            Name = "Jardinería y Bricolaje"
                        });
                });

            modelBuilder.Entity("Retail.Domain.Product", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Discount")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductId");

                    b.HasIndex("Category");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            ProductId = new Guid("cd1671d1-67bf-45c3-8a7b-a7d34dfb0b2e"),
                            Category = 1,
                            Description = "Hdr280f00b Blanca Clase A",
                            Discount = 10,
                            ImageUrl = "https://images.fravega.com/f300/c3cd04fe9a57248e4e02147c3a578911.jpg.webp",
                            Name = "Heladera con Freezer Drean",
                            Price = 590000.00m
                        },
                        new
                        {
                            ProductId = new Guid("965376b8-8f5d-4a6b-a971-7ed3de5019cf"),
                            Category = 1,
                            Description = "Carga Frontal 6Kg 800 RPM Drean Next 6.08 ECO",
                            Discount = 10,
                            ImageUrl = "https://images.fravega.com/f300/bc553a4d53bb5eb5f9e44184047b212b.jpg.webp",
                            Name = "Lavarropas Drean Netx",
                            Price = 670000.00m
                        },
                        new
                        {
                            ProductId = new Guid("1364cf0d-fb53-4013-9a3a-90d0700c3cf8"),
                            Category = 1,
                            Description = "Gas Natural 51 Cm",
                            Discount = 10,
                            ImageUrl = "https://images.fravega.com/f300/45826c7ab2451580e1ce693f2ee09679.jpg.webp",
                            Name = "Cocina Escorial Candor S2",
                            Price = 250000.00m
                        },
                        new
                        {
                            ProductId = new Guid("d4fa0a52-da00-4cfb-b6ec-9d5f106594ab"),
                            Category = 1,
                            Description = "CE-14LBL 14Lts",
                            Discount = 10,
                            ImageUrl = "https://images.fravega.com/f300/50dd572c565d2d989cf43e709b626fcc.jpg.webp",
                            Name = "Calefón Tiro Natural Escorial",
                            Price = 280000.00m
                        },
                        new
                        {
                            ProductId = new Guid("f400ab17-dc48-4494-b38d-7a63c08c409d"),
                            Category = 2,
                            Description = "128GB Azul",
                            Discount = 10,
                            ImageUrl = "https://images.fravega.com/f300/332a2d22382f714d26253b62446af895.png.webp",
                            Name = "Celular Motorola G23",
                            Price = 350000.00m
                        },
                        new
                        {
                            ProductId = new Guid("7420e468-b41b-4ccd-942e-0a00413bca15"),
                            Category = 2,
                            Description = "5G 256GB Graphite",
                            Discount = 10,
                            ImageUrl = "https://images.fravega.com/f300/332a2d22382f714d26253b62446af895.png.webp",
                            Name = "Celular Samsung Galaxy A54",
                            Price = 840000.00m
                        },
                        new
                        {
                            ProductId = new Guid("da0c87bb-3ebd-4253-b88b-c11315367195"),
                            Category = 2,
                            Description = "1 TB Carbon Black",
                            Discount = 10,
                            ImageUrl = "https://images.fravega.com/f300/bb99d78e3f2bffdc9ac01d6d4cc46761.jpg.webp",
                            Name = "Xbox Serie S",
                            Price = 1050000.00m
                        },
                        new
                        {
                            ProductId = new Guid("a513c9d1-c238-4e2c-866f-bce0294a2a64"),
                            Category = 2,
                            Description = "14” Intel Celeron 4GB 256GB SSD 14-DQ0515LA",
                            Discount = 10,
                            ImageUrl = "https://images.fravega.com/f300/332a2d22382f714d26253b62446af895.png.webp",
                            Name = "Notebook HP",
                            Price = 500000.00m
                        },
                        new
                        {
                            ProductId = new Guid("bca166c8-635c-4162-b276-034bc410db17"),
                            Category = 3,
                            Description = "Malla Metal Rosa",
                            Discount = 10,
                            ImageUrl = "https://images.fravega.com/f300/480b83219a6b568d223a684bc320077c.jpg.webp",
                            Name = "Reloj Inteligente Mujer Smartwatch Nictom",
                            Price = 35000.00m
                        },
                        new
                        {
                            ProductId = new Guid("639d6f36-0412-4191-a49f-eebb20082734"),
                            Category = 3,
                            Description = "Sumergible negro",
                            Discount = 10,
                            ImageUrl = "https://images.fravega.com/f300/d3e720120971297c2af0c5e6a4d7c21d.jpg.webp",
                            Name = "Reloj Digital Deportivo Gadnic Apolo",
                            Price = 38560.00m
                        },
                        new
                        {
                            ProductId = new Guid("537b6897-94e1-4284-91a4-228982a9bcde"),
                            Category = 3,
                            Description = "TWS W-1 Black AYV0125, Rosa duracion bateria 4hs",
                            Discount = 10,
                            ImageUrl = "https://images.fravega.com/f300/de17587debfa3603efd00fc8b5211a02.jpg.webp",
                            Name = "Auriculares Suono Bluetooth",
                            Price = 7900.00m
                        },
                        new
                        {
                            ProductId = new Guid("e992942a-080b-4833-b7d5-775de466133f"),
                            Category = 3,
                            Description = "Negro,duracion bateria 4hs, formato vincha.",
                            Discount = 10,
                            ImageUrl = "https://images.fravega.com/f300/7f960ce8079a14e7b29a13eb2faf36ed.jpg.webp",
                            Name = "Auriculares Bluetooth Deportivos Suono S9",
                            Price = 5000.00m
                        },
                        new
                        {
                            ProductId = new Guid("6e72c92b-6043-4286-af8e-085ce3002100"),
                            Category = 4,
                            Description = "190 x 140 cm",
                            Discount = 10,
                            ImageUrl = "https://images.fravega.com/f300/1feb1913552f204a9f996da857073ff8.jpg.webp",
                            Name = "Sommier y Colchón de Resortes Piero Genova",
                            Price = 295000.00m
                        },
                        new
                        {
                            ProductId = new Guid("5504945a-19b6-4ba3-a76a-ebf609be1da2"),
                            Category = 4,
                            Description = "12 box de guardado de 28 x 28 - 4 cajones 59 ancho x 36 profundidad x 16 alto - Sector Colgado 171,5 x 56",
                            Discount = 10,
                            ImageUrl = "https://images.fravega.com/f300/dad338848c2a997aaa0b0d151d5995e2.png.webp",
                            Name = "Placard Perfileria de Aluminio Carpinteria Rivadavia Linea Delta",
                            Price = 284731.00m
                        },
                        new
                        {
                            ProductId = new Guid("4aca5e34-b9c8-47a8-85ef-f19cd711a1de"),
                            Category = 4,
                            Description = "Almohadón Pack X4 Negra Hdc Group",
                            Discount = 10,
                            ImageUrl = "https://images.fravega.com/f300/b5239d43444fcfb8c5cda9513a0feafc.jpg.webp",
                            Name = "Silla Tulip ",
                            Price = 110000.00m
                        },
                        new
                        {
                            ProductId = new Guid("62fa6192-5272-4ebb-8aa8-b2c1e717906f"),
                            Category = 4,
                            Description = "3 Cuerpos De Chenille Gris Oscuro Full Confort",
                            Discount = 10,
                            ImageUrl = "https://images.fravega.com/f300/2cd28c520d9b3fc4213e84615c348155.jpg.webp",
                            Name = "Sillón Trento",
                            Price = 488210.00m
                        },
                        new
                        {
                            ProductId = new Guid("dc587fe0-cb79-4ed4-9e54-0fceb253bc2b"),
                            Category = 5,
                            Description = "Set de 12 Pinceles y Brochas para Ojos y Cejas es un imprescindible para cualquier amante del maquillaje.",
                            Discount = 10,
                            ImageUrl = "https://images.fravega.com/f300/f523ff12a303961b3f297875489d1790.jpg.webp",
                            Name = "Set 12 Pinceles Brochas para Ojos Cejas Daikon ",
                            Price = 16800.00m
                        },
                        new
                        {
                            ProductId = new Guid("39248fec-e949-40d9-be22-f92533c08f82"),
                            Category = 5,
                            Description = "Plegable Aumento Portátil Daikon BMF005",
                            Discount = 10,
                            ImageUrl = "https://images.fravega.com/f300/d6732cc7dab813c98be547482699fce0.jpg.webp",
                            Name = "Espejo Luz LED Maquillaje",
                            Price = 15200.00m
                        },
                        new
                        {
                            ProductId = new Guid("06ed7287-3021-464f-8f36-1abc0e5c848e"),
                            Category = 5,
                            Description = "Esta garantiza un secado y curado veloz gracias a sus 80w y 36 luces LED.",
                            Discount = 10,
                            ImageUrl = "https://images.fravega.com/f300/02e234f30d04bf0624f6ec2cc28a1c82.jpg.webp",
                            Name = "Cabina Uv Led Sun",
                            Price = 21600.00m
                        },
                        new
                        {
                            ProductId = new Guid("2c1fe04e-d248-4786-9aac-00e75a79a771"),
                            Category = 5,
                            Description = " COLORES BLANCA Y ROSA",
                            Discount = 10,
                            ImageUrl = "https://images.fravega.com/f300/acb620d996dd7c6d0b6404770b2c669c.jpg.webp",
                            Name = "Daikon Perfiladora De Cejas AE 302",
                            Price = 9600.00m
                        },
                        new
                        {
                            ProductId = new Guid("3bdcf679-4fee-47d3-ad78-7d0e0a64b8e3"),
                            Category = 6,
                            Description = "Mancuernas 25kg 47cm de largo, barra extensora 8 Discos de 1.25Kg ",
                            Discount = 10,
                            ImageUrl = "https://images.fravega.com/f300/49e2a4bd8a16dfe0681e5d78f7d83726.jpg.webp",
                            Name = "Kit Funcional Mancuernas + Barra 25Kg Randers",
                            Price = 9600.00m
                        },
                        new
                        {
                            ProductId = new Guid("993edbc6-32c9-4bd5-9f99-5dd5288fa709"),
                            Category = 6,
                            Description = "Peso máximo soportado 120kg",
                            Discount = 10,
                            ImageUrl = "https://images.fravega.com/f300/727c29cee54e6942d3804459c6c5839f.jpg.webp",
                            Name = "Bicicleta Fija Gfitness L-001A Plateada",
                            Price = 379000.00m
                        },
                        new
                        {
                            ProductId = new Guid("02ad0b96-26e5-43c1-ac10-17f06b5dba34"),
                            Category = 6,
                            Description = "Mancuernas 25kg 47cm de largo",
                            Discount = 10,
                            ImageUrl = "https://images.fravega.com/f300/061c85fd9c81ccda6359407d911a9ed9.jpg.webp",
                            Name = "Tabla para Abdominales con Mancuernas Randers",
                            Price = 130000.00m
                        },
                        new
                        {
                            ProductId = new Guid("03c2cc0d-071a-4de5-b091-e5d06f10ee04"),
                            Category = 6,
                            Description = "La PVC Yoga Mat para yoga está hecha de PVC espumado.",
                            Discount = 10,
                            ImageUrl = "https://images.fravega.com/f300/d5adca919b008c4c12448963d74d61f4.jpg.webp",
                            Name = "Yoga Mat PVC 4mm MD9010-R Gfitness",
                            Price = 9100.00m
                        },
                        new
                        {
                            ProductId = new Guid("1817167f-42cd-4e5b-ad87-592d63ff01d8"),
                            Category = 7,
                            Description = "Encantadoras muñecas",
                            Discount = 10,
                            ImageUrl = "https://images.fravega.com/f300/c6d0a55724ade8e6f7f6e7e83bdfaca5.png.webp",
                            Name = "Cry Babies Dressy Fancy",
                            Price = 50000.00m
                        },
                        new
                        {
                            ProductId = new Guid("1adf1af7-041f-4a92-ac5d-f2059dc8bc20"),
                            Category = 7,
                            Description = "Edad recomendada: +3 años",
                            Discount = 10,
                            ImageUrl = "https://images.fravega.com/f300/31428ce9faa9608dc8f43daaf50fc299.jpg.webp",
                            Name = "Juliana Tienda De Donas",
                            Price = 34482.00m
                        },
                        new
                        {
                            ProductId = new Guid("0dad3207-b1dd-4733-a439-fbef82c4f6b2"),
                            Category = 7,
                            Description = "Estimula el pensamiento constructivo, espacial y abstracto.",
                            Discount = 10,
                            ImageUrl = "https://images.fravega.com/f300/d5adca919b008c4c12448963d74d61f4.jpg.webp",
                            Name = "Bloques Magnéticos Para Armar 18 Piezas",
                            Price = 24011.00m
                        },
                        new
                        {
                            ProductId = new Guid("67d70676-decf-4f08-8aa8-bbe77db48eee"),
                            Category = 7,
                            Description = "cocina infantil de juguete es una gran opción para los niños que aman cocinar.",
                            Discount = 10,
                            ImageUrl = "https://images.fravega.com/f300/d5adca919b008c4c12448963d74d61f4.jpg.webp",
                            Name = "Duravit Mi Cocina 33 Piezas",
                            Price = 16030.00m
                        },
                        new
                        {
                            ProductId = new Guid("78436472-8d7e-418c-9ff7-f9f6a56bea5b"),
                            Category = 8,
                            Description = "100% yerba mate (ilex paraguariensis)",
                            Discount = 10,
                            ImageUrl = "https://jumboargentina.vtexassets.com/arquivos/ids/711224-800-auto?v=637938633804770000&width=800&height=auto&aspect=true",
                            Name = "Yerba Mate Playadito Suave 1 Kg",
                            Price = 4845.00m
                        },
                        new
                        {
                            ProductId = new Guid("31b23593-4a27-4616-9b73-f80053b92c45"),
                            Category = 8,
                            Description = "172 Gr Harina de trigo 000, hierro, ácido fólico, tiamina (b1), riboflavina (b2), niacina, azúcar, emu ins 442",
                            Discount = 10,
                            ImageUrl = "https://jumboargentina.vtexassets.com/arquivos/ids/791393-800-auto?v=638288337779830000&width=800&height=auto&aspect=true",
                            Name = "Galletitas Con Chips De Chocolate Cuisine",
                            Price = 1350.00m
                        },
                        new
                        {
                            ProductId = new Guid("ee1425ad-4935-49b4-9c73-f10061dccbe0"),
                            Category = 8,
                            Description = "Aguas Minerales sin Gas",
                            Discount = 10,
                            ImageUrl = "https://jumboargentina.vtexassets.com/arquivos/ids/619126-800-auto?v=637457162754830000&width=800&height=auto&aspect=true",
                            Name = "Agua Mineral Sin Gas Cuisine-co 2 L",
                            Price = 850.00m
                        },
                        new
                        {
                            ProductId = new Guid("b6710fa6-80f6-4919-aeec-1636976b297e"),
                            Category = 8,
                            Description = "Aguas Saborizadas con Gas",
                            Discount = 10,
                            ImageUrl = "https://jumboargentina.vtexassets.com/arquivos/ids/769370-800-auto?v=638120073844000000&width=800&height=auto&aspect=true",
                            Name = "Gaseosa H2oh Naranchelo 2,25 L",
                            Price = 2047.50m
                        },
                        new
                        {
                            ProductId = new Guid("dd7c0794-320b-48b5-a634-fb33a5ed5b1a"),
                            Category = 9,
                            Description = "ESPIRAL A4 X 80 RAY.",
                            Discount = 10,
                            ImageUrl = "https://tiotomar.vtexassets.com/arquivos/ids/170536-800-800?v=637937572304970000&width=800&height=800&aspect=true",
                            Name = "CUADERNO SETTER GEOMETRY",
                            Price = 3700.50m
                        },
                        new
                        {
                            ProductId = new Guid("7cc333fa-b924-49df-928a-f138236cc42c"),
                            Category = 9,
                            Description = "N.5 COLOR X 24 H.",
                            Discount = 10,
                            ImageUrl = "https://tiotomar.vtexassets.com/arquivos/ids/226689-800-800?v=638423970202100000&width=800&height=800&aspect=true",
                            Name = "BLOCK SETTER DIBUJO",
                            Price = 3990.50m
                        },
                        new
                        {
                            ProductId = new Guid("d811150c-9f20-4262-bc3c-fe822c817525"),
                            Category = 9,
                            Description = "Cuerpo de resina plastica. No se astilla al sacarle punta",
                            Discount = 9,
                            ImageUrl = "https://tiotomar.vtexassets.com/arquivos/ids/167138-800-800?v=637937554688800000&width=800&height=800&aspect=true",
                            Name = "LAPIZ GRAFITO BIC EVOLUTION ",
                            Price = 1890.50m
                        },
                        new
                        {
                            ProductId = new Guid("88f03a3f-0131-4a81-9e15-5861e3c26c17"),
                            Category = 9,
                            Description = "12 U Los nuevos colores SuperSoft tienen colores mucho mas vivos y ecologicos",
                            Discount = 9,
                            ImageUrl = "https://tiotomar.vtexassets.com/arquivos/ids/173873-800-800?v=637937587983730000&width=800&height=800&aspect=true",
                            Name = "LAPICES FABER CASTELL SUPERSOFT",
                            Price = 14900.50m
                        },
                        new
                        {
                            ProductId = new Guid("350408cf-c437-4b8a-8ef6-641b03e56ef2"),
                            Category = 10,
                            Description = "8 piezas livianas y fabricadas con materiales de alta calidad",
                            Discount = 10,
                            ImageUrl = "https://images.fravega.com/f300/21cb40b3ef663bd75715a2aea63e7843.jpg.webp",
                            Name = "Set Kit Jardineria Sweet Garden Con Cinturon Tramontina",
                            Price = 65956.00m
                        },
                        new
                        {
                            ProductId = new Guid("dfb064d4-1fee-41c7-a4ee-4d53f97a007c"),
                            Category = 10,
                            Description = "Hechas de metal y plástico resistentes",
                            Discount = 10,
                            ImageUrl = "https://images.fravega.com/f300/6e80c3f28a89404ee55a5da927d97546.jpg.webp",
                            Name = "Kit de Jardinería Gadnic",
                            Price = 33000.00m
                        },
                        new
                        {
                            ProductId = new Guid("83cf0519-76f8-4b67-ae12-7a9285373251"),
                            Category = 10,
                            Description = "motor eléctrico y una potencia de 1000 watts",
                            Discount = 10,
                            ImageUrl = "https://images.fravega.com/f300/ae1c68f705650940d5a14fdad43fdaf3.jpg.webp",
                            Name = "Bordeadora Eléctrica Severbon",
                            Price = 60000.00m
                        },
                        new
                        {
                            ProductId = new Guid("5afd5f87-daa9-4e33-a302-5d8728b361a7"),
                            Category = 10,
                            Description = "Incluye: Pistola, manguera de 5 m, dispensador de detergente integrado. 2000 W",
                            Discount = 10,
                            ImageUrl = "https://images.fravega.com/f300/479643aca88b3f806fe312f688512467.jpg.webp",
                            Name = "Hidrolavadora Eléctrica Daewoo",
                            Price = 220000.00m
                        });
                });

            modelBuilder.Entity("Retail.Domain.Sale", b =>
                {
                    b.Property<int>("SaleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SaleId"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Taxes")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalDiscount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalPlay")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("SaleId");

                    b.ToTable("Sale");
                });

            modelBuilder.Entity("Retail.Domain.SaleProduct", b =>
                {
                    b.Property<int>("ShoppingCartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShoppingCartId"));

                    b.Property<int>("Discount")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("Product")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductoProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Sale")
                        .HasColumnType("int");

                    b.Property<int>("VentaSaleId")
                        .HasColumnType("int");

                    b.HasKey("ShoppingCartId");

                    b.HasIndex("ProductoProductId");

                    b.HasIndex("VentaSaleId");

                    b.ToTable("SaleProduct");
                });

            modelBuilder.Entity("Retail.Domain.Product", b =>
                {
                    b.HasOne("Retail.Domain.Category", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("Category")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("Retail.Domain.SaleProduct", b =>
                {
                    b.HasOne("Retail.Domain.Product", "Producto")
                        .WithMany("VentaProductos")
                        .HasForeignKey("ProductoProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Retail.Domain.Sale", "Venta")
                        .WithMany("VentaProductos")
                        .HasForeignKey("VentaSaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("Retail.Domain.Category", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("Retail.Domain.Product", b =>
                {
                    b.Navigation("VentaProductos");
                });

            modelBuilder.Entity("Retail.Domain.Sale", b =>
                {
                    b.Navigation("VentaProductos");
                });
#pragma warning restore 612, 618
        }
    }
}
